### ISSUE TITLE
Remove PHP File Associations

### ISSUE THREAD

**Issue by blake-walters** [slackhq/vscode-hack#121]
I have to disable this extension when working on a PHP project so that my PHP extension functions correctly. Not huge but kinda annoying, especially as hack/hhvm no longer supports PHP.

**Comment by PranayAgarwal** [comment]
This isn't going to work because a lot of Hack codebases (including at Slack) have a large number of `.php` files (`.hack` as an extension was added relatively recently). A good workaround is to add a file association in your workspace config in the PHP-only project. This way the files will be detected as PHP and picked up by the PHP extension(s).

```json
  "files.associations": {
    "*.php": "php"
  },
```

**Comment by blake-walters** [comment]
Thanks for the workaround Pranay, I'll give that a try.
